name: 5 - 1 - Event Filters and Activity Types
on:
  push:
    branches: [main]
  pull_request: [opened, synchronize]
  branches: [main]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the event name
        run: echo "Running whenever a PR is opened or synchronize and branch is main"